<!-- Explain why you chose this topic, and the questions you are interested in studying. 
Provide context for readers who are not familiar with the topic.
suggested: 1 page = 250 words
 -->

# Introduction
Obesity is an escalating global pandemic that has taken over many countries in the world. Overweight and obesity are the [fifth leading risk for global deaths](https://easo.org/media-portal/statistics/), and a leading preventable cause of death ([only second to smoking in the US](https://healthpolicy.usc.edu/article/obesity-second-to-smoking-as-the-most-preventable-cause-of-us-deaths-needs-new-approaches)).

With [more than 40% of Americans being obese](https://www.cdc.gov/obesity/data/adult.html), our team was outraged by the scale of this problem. Being obese not only has detrimental effects on a person's health, it also drastically impacts their self-confidence and self-image. While great efforts have been made by body positivity activists to encourage people to embrace their appearances regardless of their size, it is undeniable that people who are overweight still face a great deal of prejudice and inconveniences in their daily lives that can be easily resolved, if only they were able to lose weight by leading a healthier lifestyle. 

In order to tackle this problem, we seek to understand what health and physical factors are typically associated with obesity. This will be useful to the community in two ways: 

1. Empower overweight individuals by allowing them to understand what factors might have contributed to or have been caused by their weight. 
2. Increase general understanding of the problem of obesity such that the non-obese population is more empathetic towards obese individuals. 

In this project, we use techniques learnt in the course "Exploratory Data Analysis and Visualization" by Professor Joyce Robbins at Columbia University to inspect our chosen dataset from many angles, describing and summarizing the dataset without making any precise assumptions about the data. Here is a quick overview of the other pages:
- [2. Data](https://hide-a-pumpkin.github.io/Obesity-Data-Analysis/data.html): Presentation of our dataset and research methodology
- [3. Results](https://hide-a-pumpkin.github.io/Obesity-Data-Analysis/results.html): The exploratory techniques used on the dataset and our findings
- [4. Interactive graph](https://hide-a-pumpkin.github.io/Obesity-Data-Analysis/d3graph.html): Interactive parallel coordinates plot to visualize relationships between variables
- [5. Conclusion](https://hide-a-pumpkin.github.io/Obesity-Data-Analysis/conclusion.html): Key findings of our exploration, limitations of our analyses and future directions.  