---
title: "visualization-mosaic"
output: html_document
date: "2023-12-11"
---

```{r setup, include=FALSE}
library(readr)
library(dplyr)
library(tidyverse)
library(stats)
library(vcd)
library(ggplot2)
library(gridExtra)


data <- read_csv('CleanObesityDataSet.csv',show_col_types = FALSE)
```

```{r summary}
cat("Number of rows in dataset: ", nrow(data))
cat("\nNumber of columns in dataset: ", ncol(data))
cat("\nNumber of missing values in dataset: ", sum(is.na(data)))
```

```{r boxplot}
# Boxplot to visualize the BMI across all individuals 
ggplot(data, aes(x=BMI)) + 
  geom_boxplot(fill = "lightblue", color = "black") + 
  coord_cartesian(ylim = c(-2, 2)) +  
  labs(title = "Boxplot of BMI across all individuals")
```

```{r fivenum}
fivenum(data$BMI)
```

```{r histogram}
plot1 <- ggplot(data = data, aes(x = Height)) + geom_histogram(binwidth = 0.02)
plot2 <- ggplot(data = data, aes(x = Weight)) + geom_histogram(binwidth = 2)
plot3 <- ggplot(data = data, aes(x = BMI)) + geom_histogram(binwidth = 1)
grid.arrange(plot1, plot2, plot3, ncol = 3)
```

```{r shapiro tests, fig.width = 10}
shapiro.test(data$Height)
shapiro.test(data$Weight)
shapiro.test(data$BMI)
```
```{r qqplot, fig.width = 15}
plot1 <- ggplot(data, aes(sample = Height)) + 
  stat_qq() + 
  stat_qq_line(col = "navy")

plot2 <- ggplot(data, aes(sample = Weight)) + 
  stat_qq() + 
  stat_qq_line(col = "navy")

plot3 <- ggplot(data, aes(sample = BMI)) + 
  stat_qq() + 
  stat_qq_line(col = "navy")

grid.arrange(plot1, plot2, plot3, ncol = 3)

```


```{r alluvial diagrams}
library(ggalluvial) 
library(dplyr)

data <- read_csv('CleanObesityDataSet.csv',show_col_types = FALSE)

data_alluvial <- data[c("Age", "NObeyesdad", "NCP", "CH2O", "FAF", "CALC", "TUE")]

data_alluvial$CH2O <- as.numeric(data_alluvial$CH2O)
data_alluvial$CH2O <- round(data_alluvial$CH2O)
data_alluvial$NCP <- as.numeric(data_alluvial$NCP)
data_alluvial$NCP <- round(data_alluvial$NCP)
data_alluvial$FAF <- as.numeric(data_alluvial$FAF)
data_alluvial$FAF <- round(data_alluvial$FAF)
data_alluvial$TUE <- as.numeric(data_alluvial$TUE)
data_alluvial$TUE <- round(data_alluvial$TUE)

data_alluvial <- data_alluvial %>%
 mutate(Obesity_Category = case_when(
   NObeyesdad %in% c("Overweight_Level_I", "Overweight_Level_II") ~ "Overweight",
   NObeyesdad %in% c("Obesity_Type_I", "Obesity_Type_II") ~ "Obese",
   NObeyesdad == "Normal_Weight" ~ "Normal",
   NObeyesdad == "Insufficient_Weight" ~ "Underweight"
 ))


data_alluvial_1 <- dplyr::count_(data_alluvial,vars = c("Obesity_Category", "NCP", "CH2O"))

colnames(data_alluvial_1)[colnames(data_alluvial_1) == "n"] <- "Freq"

data_alluvial_1$Obesity_Category <- factor(data_alluvial_1$Obesity_Category, levels = c("Underweight", "Normal", "Overweight", "Obese"))

data_alluvial_1

png("5_alluvial_NCP_CH2O.png")
ggplot(as.data.frame(data_alluvial_1), aes(y = Freq, axis1 = Obesity_Category, axis2 = NCP, axis3 = CH2O)) +
  geom_alluvium(aes(fill = Obesity_Category), width = 1/12) +
  geom_stratum(width = 1/12, fill = "grey80", color = "grey") +
  geom_label(stat = "stratum", aes(label = after_stat(stratum))) +
  scale_x_discrete(limits = c("Gender", "Dept"), expand = c(.05, .05)) +
#  layout(margin = list(b = 90) +
  scale_fill_brewer(type = "qual", palette = "Set1")  + 
  expand_limits(x = 0, y = 0) +
  ggtitle("Dietary and exercise habits of the population") + 
  theme_void() +
  theme(plot.margin = margin(0,0,0,0, "cm"))
dev.off()
```
```{r alluvium 2}
data_alluvial_2 <- dplyr::count_(data_alluvial,vars = c("Obesity_Category", "FAF", "CALC", "TUE"))

colnames(data_alluvial_2)[colnames(data_alluvial_2) == "n"] <- "Freq"

data_alluvial_2$Obesity_Category <- factor(data_alluvial_2$Obesity_Category, levels = c("Underweight", "Normal", "Overweight", "Obese"))

data_alluvial_2

png("5_alluvial_Physical activity frequency_alcohol_time on tech device.png")
ggplot(as.data.frame(data_alluvial_2), aes(y = Freq, axis1 = Obesity_Category, axis2 = FAF, axis3 = CALC, axis4 = TUE)) +
  geom_alluvium(aes(fill = Obesity_Category), width = 1/12) +
  geom_stratum(width = 1/12, fill = "grey80", color = "grey") +
  geom_label(stat = "stratum", aes(label = after_stat(stratum))) +
  scale_x_discrete(limits = c("Gender", "Dept"), expand = c(.05, .05)) +
#  layout(margin = list(b = 90) +
  scale_fill_brewer(type = "qual", palette = "Set1")  + 
  expand_limits(x = 0, y = 0) +
  ggtitle("Physical activity frequency vs alcohol vs time on tech device") + 
  theme_void() +
  theme(plot.margin = margin(0,0,0,0, "cm"))
#dev.off()
```

```{r mosaic}
# plot 1 mosaic 3 var
library(colorspace)
library(plyr)
library("dplyr")
#data_mosaic <- table(data[c("Gender", "family_history_with_overweight", "FAVC", "SCC", "IsOverweight")])

data_mosaic <- data[c("FAVC", "SCC", "IsOverweight")] 

data_mosaic <- dplyr::count_(data_mosaic,vars = c("FAVC", "SCC", "IsOverweight"))

colnames(data_mosaic)[colnames(data_mosaic) == "n"] <- "Freq"

# colnames(data_mosaic)[colnames(data_mosaic) == "n"] <- "Frequent consumption of high calories (FAVC)"

data_mosaic

subs_pal <- colorspace::qualitative_hcl(2)

data_mosaic$IsOverweight <- fct_rev(as.character(data_mosaic$IsOverweight))

png("1_mosaic_favc-scc-overweight.png")

mosaic(FAVC ~ SCC + IsOverweight, data = data_mosaic, direction = c("v","v","h"), highlighting_fill = c("#bdd7e7","#2171b5"), xlab ="Test")


# mosaic(FAVC ~ SCC + IsOverweight, data = data_mosaic, direction = c("v","v","h"), highlighting_fill = c("#bdd7e7","#2171b5"), ylab = "Frequent consumption of high caloric food (FAVC)", main = "Frequent consumption of high calories (FAVC) \n vs Calories consumption monitoring (SCC) vs IsOverweight") 

dev.off()


```

```{r pressure, echo=FALSE}
plot(pressure)
```
